server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/css application/javascript image/svg+xml;
    gzip_min_length 256;

    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;

    # assets com cache curto (evita guardar 404/cache velho)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|webp|woff2?)$ {
        expires 1h;
        add_header Cache-Control "public, max-age=3600";
    }

    # mapeamento de rotas (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
